# COMMON SPRING CONFIGURATION

spring:
  profiles:
    active: "${spring_profile_active:local}"
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    initialize: true
    continue-on-error: true
    tomcat:
      connection-properties: stringtype=unspecified
  resources:
    chain:
      enabled: true
  main:
    banner-mode: "off"
  jpa:
    generate-ddl: true

#Logging
logging:
  level:
    root: INFO
    org.springframework.web: WARN

server:
  port: 8080

security:
  ignored: /favicon.ico,/lib/**,/resources/**,/v1/api-docs,/oauth/token,/swagger-ui.html,/webjars/springfox-swagger-ui/**,/configuration/security/**,/swagger-resources,/configuration/ui,/v2/api-docs,/swagger-resources/configuration/**

---
# ----------------------------------------------------------------------------------
# Local profile configuration
# ----------------------------------------------------------------------------------
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://192.168.43.254:5432/userdb
    username: postgres
    password: postgres

security:
   oauth2:
      resource:
         service-id: yash-client
         filter-order: 3
---

# ----------------------------------------------------------------------------------
# Development profile configuration
# ----------------------------------------------------------------------------------
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

security:
   oauth2:
      resource:
         service-id: sftpro-client
         filter-order: 3
---
# ----------------------------------------------------------------------------------
# Production profile configuration
# ----------------------------------------------------------------------------------
spring:
  profiles: prod
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

security:
   oauth2:
      resource:
         service-id: sftpro-client
         filter-order: 3
---